permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  projects:
    output: true
    permalink: /:collection/:path/

exclude: ["assets/node_modules", "vendor"]

defaults:
  - scope:
      path: ""
    values:
      lang: en
      layout: default
  - scope:
      path: _posts/fr
    values:
      lang: fr
  - scope:
      path: _posts/es
    values:
      lang: es

  - scope:
      path: _projects/en
      type: project
    values:
      lang: en
      layout: default

  - scope:
      path: _projects/fr
      type: projects
    values:
      lang: fr

  - scope:
      path: _projects/es
      type: projects
    values:
      lang: es

nav:
  en:
    blog:
      title: "Notes"
      url:   "/"
    about:
      title: "About"
      url:   "/about/"
    projects:
      title: "Projects"
      url:   "/projects"
  fr:
    blog:
      title: "Notes"
      url:   "/notes/"
    about:
      title: "À propos"
      url:   "/a-propos/"
    projects:
      title: "Projets"
      url:   "/projets"
  es:
    blog:
      title: "Notas"
      url:   "/notas/"
    about:
      title: "Sobre mí"
      url:   "/sobre-mi/"
    projects:
      title: "Proyectos"
      url:   "/proyectos"

t:
  en:
    title: "Personal website of Maxime Laforet"
    url:   "/"
    photoCredit: "Photography:"
  fr:
    title: "Site web personnel de Maxime Laforet"
    url:   "/notes/"
    photoCredit: "Photographie :"
  es:
    title: "Web personal de Maxime Laforet"
    url:   "/notas/"
    photoCredit: "Fotografía:"
